language: rust
rust: [stable, beta, nightly]
cache: cargo
env:
  matrix:
    - RELEASE_FLAG=""
    - RELEASE_FLAG="--release"

install:
  - "export RUSTFLAGS=$(cargo --version | grep nightly >/dev/null && echo \"-Z external-macro-backtrace\")"
  - "rustup component add rustfmt --toolchain $(rustup show active-toolchain | cut -d\" \" -f1)"
  - cargo install just wasm-pack

script:
  - cargo fmt --all -- --check
  - just build
  - cargo check --all --verbose $RELEASE_FLAG
  - cargo build --all --verbose $RELEASE_FLAG
  - cargo test --all --verbose $RELEASE_FLAG
